In [1]:
import numpy as np

In [2]:
# Input
z = np.array([[37, 20, 12],
              [15, 32, 4],
              [5,  40, 2]
             ])
r = np.array([[435],[178],[70]])

## Method 1: Using inverse of matrix

In [3]:
print(np.linalg.inv(z))
X = np.linalg.inv(z).dot(r)
print(X)

[[-0.06282723  0.28795812 -0.19895288]
 [-0.0065445   0.0091623   0.02094241]
 [ 0.28795812 -0.90314136  0.57853403]]
[[10.  ]
 [ 0.25]
 [ 5.  ]]


## Method 2: Using solve() function

In [4]:
y = np.linalg.solve(z,r)
print(y)

[[10.  ]
 [ 0.25]
 [ 5.  ]]


### Concatenation

In [5]:
a = np.array([[37, 20, 12]])
b = np.array([[15, 32, 4]])
c = np.array([[5,  40, 2]])

u = np.concatenate((a, b, c), axis=0)
print(u)

[[37 20 12]
 [15 32  4]
 [ 5 40  2]]
