# Scientific Computing & NumPy Basics

## NumPy Arrays

In [1]:
import numpy as np

a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
b = np.array([1, 2, 'a'])
b

array(['1', '2', 'a'], dtype='<U21')

In [4]:
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
zero_array = np.zeros((2, 2))  # 2 by 2 zero matrix
zero_array

array([[0., 0.],
       [0., 0.]])

In [6]:
one_array = np.ones((2, 2, 3), dtype=int)  # 3D one integer matrix
one_array

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [8]:
rand_array = np.random.rand(2, 3)
rand_array

array([[0.90581261, 0.88732623, 0.291661  ],
       [0.44705149, 0.25966191, 0.73547706]])

In [9]:
a = np.array([1, 2, 3])
a[0]

1

In [10]:
a[1]

2

In [12]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
b[1, 1]  # commas are used when the array has many dimensions

5

In [2]:
a = np.random.rand(2, 3, 4)  # random 2-by-3-by-4 matrix
a

array([[[0.54376986, 0.00244875, 0.74179644, 0.14304955],
        [0.77229612, 0.32254451, 0.0778769 , 0.2832851 ],
        [0.26492963, 0.5217093 , 0.68267418, 0.29538502]],

       [[0.94479229, 0.28608588, 0.52837161, 0.18493272],
        [0.08970716, 0.00239815, 0.80097454, 0.74721516],
        [0.70845696, 0.09788526, 0.98864408, 0.82521871]]])

In [6]:
a[1, 0: 2, 1:]  # accessing numbers that are in the second element in 1st axis
                # first two elements in 2nd axis, and last three elements in 3rd axis

array([[0.28608588, 0.52837161, 0.18493272],
       [0.00239815, 0.80097454, 0.74721516]])

In [7]:
a

array([[[0.54376986, 0.00244875, 0.74179644, 0.14304955],
        [0.77229612, 0.32254451, 0.0778769 , 0.2832851 ],
        [0.26492963, 0.5217093 , 0.68267418, 0.29538502]],

       [[0.94479229, 0.28608588, 0.52837161, 0.18493272],
        [0.08970716, 0.00239815, 0.80097454, 0.74721516],
        [0.70845696, 0.09788526, 0.98864408, 0.82521871]]])

In [9]:
a.shape  # the `shape` attributes holds the value of the current shape

(2, 3, 4)

In [11]:
np.reshape(a, (3, 2, 4))

array([[[0.54376986, 0.00244875, 0.74179644, 0.14304955],
        [0.77229612, 0.32254451, 0.0778769 , 0.2832851 ]],

       [[0.26492963, 0.5217093 , 0.68267418, 0.29538502],
        [0.94479229, 0.28608588, 0.52837161, 0.18493272]],

       [[0.08970716, 0.00239815, 0.80097454, 0.74721516],
        [0.70845696, 0.09788526, 0.98864408, 0.82521871]]])

In [12]:
np.reshape(a, (3, 3, 3))

ValueError: cannot reshape array of size 24 into shape (3,3,3)

In [14]:
a.T

array([[[0.54376986, 0.94479229],
        [0.77229612, 0.08970716],
        [0.26492963, 0.70845696]],

       [[0.00244875, 0.28608588],
        [0.32254451, 0.00239815],
        [0.5217093 , 0.09788526]],

       [[0.74179644, 0.52837161],
        [0.0778769 , 0.80097454],
        [0.68267418, 0.98864408]],

       [[0.14304955, 0.18493272],
        [0.2832851 , 0.74721516],
        [0.29538502, 0.82521871]]])