# 2.1 Scientific Computing & NumPy Basics

## 2.1.1 NumPy Arrays

In [1]:
import numpy as np

a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
b = np.array([1, 2, 'a'])
b

array(['1', '2', 'a'], dtype='<U21')

In [4]:
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
zero_array = np.zeros((2, 2))  # 2 by 2 zero matrix
zero_array

array([[0., 0.],
       [0., 0.]])

In [6]:
one_array = np.ones((2, 2, 3), dtype=int)  # 3D one integer matrix
one_array

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [8]:
rand_array = np.random.rand(2, 3)
rand_array

array([[0.90581261, 0.88732623, 0.291661  ],
       [0.44705149, 0.25966191, 0.73547706]])

In [9]:
a = np.array([1, 2, 3])
a[0]

1

In [10]:
a[1]

2

In [12]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
b[1, 1]  # commas are used when the array has many dimensions

5

In [2]:
a = np.random.rand(2, 3, 4)  # random 2-by-3-by-4 matrix
a

array([[[0.54376986, 0.00244875, 0.74179644, 0.14304955],
        [0.77229612, 0.32254451, 0.0778769 , 0.2832851 ],
        [0.26492963, 0.5217093 , 0.68267418, 0.29538502]],

       [[0.94479229, 0.28608588, 0.52837161, 0.18493272],
        [0.08970716, 0.00239815, 0.80097454, 0.74721516],
        [0.70845696, 0.09788526, 0.98864408, 0.82521871]]])

In [6]:
a[1, 0: 2, 1:]  # accessing numbers that are in the second element in 1st axis
                # first two elements in 2nd axis, and last three elements in 3rd axis

array([[0.28608588, 0.52837161, 0.18493272],
       [0.00239815, 0.80097454, 0.74721516]])

In [7]:
a

array([[[0.54376986, 0.00244875, 0.74179644, 0.14304955],
        [0.77229612, 0.32254451, 0.0778769 , 0.2832851 ],
        [0.26492963, 0.5217093 , 0.68267418, 0.29538502]],

       [[0.94479229, 0.28608588, 0.52837161, 0.18493272],
        [0.08970716, 0.00239815, 0.80097454, 0.74721516],
        [0.70845696, 0.09788526, 0.98864408, 0.82521871]]])

In [9]:
a.shape  # the `shape` attributes holds the value of the current shape

(2, 3, 4)

In [11]:
np.reshape(a, (3, 2, 4))

array([[[0.54376986, 0.00244875, 0.74179644, 0.14304955],
        [0.77229612, 0.32254451, 0.0778769 , 0.2832851 ]],

       [[0.26492963, 0.5217093 , 0.68267418, 0.29538502],
        [0.94479229, 0.28608588, 0.52837161, 0.18493272]],

       [[0.08970716, 0.00239815, 0.80097454, 0.74721516],
        [0.70845696, 0.09788526, 0.98864408, 0.82521871]]])

In [12]:
np.reshape(a, (3, 3, 3))

ValueError: cannot reshape array of size 24 into shape (3,3,3)

In [14]:
a.T

array([[[0.54376986, 0.94479229],
        [0.77229612, 0.08970716],
        [0.26492963, 0.70845696]],

       [[0.00244875, 0.28608588],
        [0.32254451, 0.00239815],
        [0.5217093 , 0.09788526]],

       [[0.74179644, 0.52837161],
        [0.0778769 , 0.80097454],
        [0.68267418, 0.98864408]],

       [[0.14304955, 0.18493272],
        [0.2832851 , 0.74721516],
        [0.29538502, 0.82521871]]])

## 2.1.3 Random Sampling

In [2]:
sample = np.random.normal()
sample

-0.43658969989465696

In [4]:
sample = np.random.normal(loc=100, scale=10)
sample

80.31187658687652

In [6]:
samples = np.random.normal(loc=100, scale=10, size=(2, 3))
samples

array([[ 82.7834678 , 109.16410976, 101.35105681],
       [112.54825751, 107.79073472,  77.70239823]])

In [7]:
samples = np.random.poisson(lam=10, size=(2, 2))
samples

array([[11, 10],
       [15, 11]])

In [10]:
np.random.randint(low=0, high=10, size=(2, 5))

array([[6, 4, 1, 3, 6],
       [0, 8, 8, 8, 8]])

In [11]:
np.random.choice([1, 3, 4, -6], size=(2, 2))

array([[1, 1],
       [1, 4]])

In [13]:
a = [1, 2, 3, 4]

for _ in range(3):
    np.random.shuffle(a)
    print(a)

[4, 1, 3, 2]
[4, 1, 2, 3]
[1, 2, 4, 3]


In [2]:
import random

random.seed(0)

In [3]:
np.random.seed(0)

# 2.2 Working with Tabular Data with Pandas

## 2.2.1 The DataFrame Object

In [2]:
import pandas as pd

my_dict = {'col1': [1, 2], 'col2': np.array([3, 4]),
           'col3': [5, 6]}

df = pd.DataFrame(my_dict)
df

col1  col2  col3
0     1     3     5
1     2     4     6

In [4]:
my_array = np.array([[1, 3, 5], [2, 4, 6]])

alt_df = pd.DataFrame(my_array, columns=['col1', 'col2', 'col3'])
alt_df

col1  col2  col3
0     1     3     5
1     2     4     6

## 2.2.2 Accessing Rows and Columns

In [3]:
df.loc[0]  # first row

col1    1
col2    3
col3    5
Name: 0, dtype: int64

In [4]:
df.loc[[0, 1]]  # first and second rows (all data)

col1  col2  col3
0     1     3     5
1     2     4     6

In [5]:
df.loc[0, ['col2', 'col3']]  # first row, 2nd and 3rd columns

col2    3
col3    5
Name: 0, dtype: int64

In [6]:
df['col3']  # third column

0    5
1    6
Name: col3, dtype: int64

In [7]:
for item in df.loc[:, 'col3']:
    print(item)

5
6


In [7]:
df.loc[0] = [3, 6, 9]  # change first row
df

col1  col2  col3
0     3     6     9
1     2     4     6

In [8]:
df['col2'] = [0, 0]  # change second column
df

col1  col2  col3
0     3     0     9
1     2     0     6

In [10]:
df['col4'] = [10, 10]
df.loc[3] = [1, 2, 3, 4]
df

col1  col2  col3  col4
0     3     0     9    10
1     2     0     6    10
3     1     2     3     4

In [12]:
df.loc[[False, True, False], [False, True, False, True]]

col2  col4
1     0    10

In [19]:
df.loc[:, df.loc[0] > 5]

col3  col4
0     9    10
1     6    10
3     3     4

## 2.2.4 Advanced Pandas Functionalities

In [3]:
df = pd.DataFrame({'x': [1, 2, -1], 'y': [-3, 6, 5], 'z': [1, 3, 2]})
df

x  y  z
0  1 -3  1
1  2  6  3
2 -1  5  2

In [4]:
df['x_squared'] = df['x'].apply(lambda x: x ** 2)
df

x  y  z  x_squared
0  1 -3  1          1
1  2  6  3          4
2 -1  5  2          1

In [5]:
df['x_squared'] = df['x'] ** 2
df

x  y  z  x_squared
0  1 -3  1          1
1  2  6  3          4
2 -1  5  2          1

In [6]:
def parity_str(x):
    if x % 2 == 0:
        return 'even'
    
    return 'odd'

df['x_parity'] = df['x'].apply(parity_str)
df

x  y  z  x_squared x_parity
0  1 -3  1          1      odd
1  2  6  3          4     even
2 -1  5  2          1      odd

In [8]:
df['x_parity']

0     odd
1    even
2     odd
Name: x_parity, dtype: object

In [7]:
pd.get_dummies(df['x_parity'])

even  odd
0     0    1
1     1    0
2     0    1