# Scientific Computing & NumPy Basics

## NumPy Arrays

In [1]:
import numpy as np

a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
b = np.array([1, 2, 'a'])
b

array(['1', '2', 'a'], dtype='<U21')

In [4]:
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
zero_array = np.zeros((2, 2))  # 2 by 2 zero matrix
zero_array

array([[0., 0.],
       [0., 0.]])

In [6]:
one_array = np.ones((2, 2, 3), dtype=int)  # 3D one integer matrix
one_array

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [8]:
rand_array = np.random.rand(2, 3)
rand_array

array([[0.90581261, 0.88732623, 0.291661  ],
       [0.44705149, 0.25966191, 0.73547706]])

In [9]:
a = np.array([1, 2, 3])
a[0]

1

In [10]:
a[1]

2

In [12]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
b[1, 1]  # commas are used when the array has many dimensions

5